### ISSUE TITLE
How to use it in the SXOS?

### ISSUE THREAD

**Issue by youtzz** [Lesking72/HBMenu-Forwarder#1]
I try to create the override_config.ini file and put it in my sdCard,but the application still doesn't work.

**Comment by Lesking72** [comment]
Did you put the file in the sxos folder? If that doesn't work it's because SX OS doesn't support override configs and the only thing you could to to change that is use a different CFW

**Comment by Lesking72** [comment]
A version has been added that does not require title override. It should work if you aren't able to make title override work.

**Comment by youtzz** [comment]
It can works!Thank you so much
